"""edited tags name too unique

Revision ID: 06000067bf60
Revises: c79f18c0c474
Create Date: 2021-06-09 17:17:46.508725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06000067bf60'
down_revision = 'c79f18c0c474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tags', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    # ### end Alembic commands ###
