"""create tables

Revision ID: cd6cd2e9fae1
Revises: a4857517702e
Create Date: 2021-06-04 16:36:21.563143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6cd2e9fae1'
down_revision = 'a4857517702e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trails', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('trails_userId_fkey', 'trails', type_='foreignkey')
    op.create_foreign_key(None, 'trails', 'users', ['user_id'], ['id'])
    op.drop_column('trails', 'userId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trails', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trails', type_='foreignkey')
    op.create_foreign_key('trails_userId_fkey', 'trails', 'users', ['userId'], ['id'])
    op.drop_column('trails', 'user_id')
    # ### end Alembic commands ###
