"""create tables

Revision ID: d5cd16138e7d
Revises: 60470838df23
Create Date: 2021-06-04 17:43:56.294252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5cd16138e7d'
down_revision = '60470838df23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jaunts', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('jaunts', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('jaunts', sa.Column('trail_id', sa.Integer(), nullable=False))
    op.alter_column('jaunts', 'blurb',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('jaunts', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'jaunts', 'trails', ['trail_id'], ['id'])
    op.drop_column('jaunts', 'endDate')
    op.drop_column('jaunts', 'startDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jaunts', sa.Column('startDate', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('jaunts', sa.Column('endDate', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'jaunts', type_='foreignkey')
    op.alter_column('jaunts', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('jaunts', 'blurb',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('jaunts', 'trail_id')
    op.drop_column('jaunts', 'start_date')
    op.drop_column('jaunts', 'end_date')
    # ### end Alembic commands ###
