"""create tables

Revision ID: 3467122b8680
Revises: d5cd16138e7d
Create Date: 2021-06-04 18:15:35.181554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3467122b8680'
down_revision = 'd5cd16138e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('blurb', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('list')
    op.add_column('jaunts', sa.Column('list_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'jaunts', 'lists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jaunts', type_='foreignkey')
    op.drop_column('jaunts', 'list_id')
    op.create_table('list',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('blurb', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='list_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='list_pkey')
    )
    op.drop_table('lists')
    # ### end Alembic commands ###
