"""create tables

Revision ID: 60470838df23
Revises: cd6cd2e9fae1
Create Date: 2021-06-04 17:02:37.673525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60470838df23'
down_revision = 'cd6cd2e9fae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('list_userId_fkey', 'list', type_='foreignkey')
    op.create_foreign_key(None, 'list', 'users', ['user_id'], ['id'])
    op.drop_column('list', 'userId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'list', type_='foreignkey')
    op.create_foreign_key('list_userId_fkey', 'list', 'users', ['userId'], ['id'])
    op.drop_column('list', 'user_id')
    # ### end Alembic commands ###
